version: '3.5'


services:
  db:
    image: postgres:15
    volumes:
      - ./Db/db.sql:/docker-entrypoint-initdb.d/db.sql
    command: postgres -c log_min_messages=FATAL -c shared_buffers=512MB
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2GB"
    networks:
      - rinha
  
  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
      - api1
      - api2
    ports:
      - "8001:8001"
    networks:
       - rinha
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "0.5GB"



  api1:
    build: 
      context: ./Api
      dockerfile: dockerfile
    image: api1
    expose:
      - "3000"
    networks:
      - rinha

  api2:
    build: 
      context: ./Api
      dockerfile: dockerfile
    image: api1
    expose:
      - "3000"
    networks:
      - rinha

networks:
  rinha:
    driver: bridge